dataset_root: '/media/lucap/big_data/datasets/repair/3D_detection_moving_camera/group_0016'
models_path: 'checkpoints'
dataset_max_size: 64
train_test_split: 0.8
num_seg_classes: 5
k: 10
use_color: False
input_features: 3
hidden_channels: 16
model: "GCN"
loss: "CROSSENTROPY"
# training
epochs: 50
print_each: 25
lr: 0.01
weight_obj: 25
show_results: True
how_many: 10
continue_training: False
ckp_path: '' # set if continue == True!
