dataset_root: '/media/lucap/big_data/datasets/repair/sand_detection_dataset_bb_yolo_1000scenes' #'/media/lucap/big_data/datasets/repair/3D_detection_moving_camera/group_0016'
models_path: 'checkpoints'
# TASK 
task: recognition
group: 29
num_classes: 5
# DATA 
train_split: 0.8
val_split: 0.1
test_split: 0.1
k: 6
add_noise: True
noise_strength: 0.08
num_splits: 10
# FEATURES
use_color: True
normalize_color: True
use_normals: True
# MODEL dimensions
model: "GCN"
input_features: 9
hidden_channels: 256
# num_seg_classes: 6
# LOSS
loss: "CAT"
# training
epochs: 2000
evaluate_and_print_each: 10
batch_size: 128
lr: 0.0005
patience: 100
weight_obj: 25
continue_training: False
ckp_path: '' # set if continue == True!
# VIS
show_results: True
how_many: 2

