detection_model_folder: 'checkpoints/sand_scene-detection-net_GCN-based_trained_on_sand_detection_dataset_bb_yolo_1000scenes_split_5_using_lossCAT_for15epochs_from_scratch_bs_1_noiseTrue'
g15_recognition_model_folder: 'checkpoints/fragment-recognition-net_GCN-based_trained_on_sand_detection_dataset_bb_yolo_1000scenes_split_7-group_0015_using_lossCAT_for500epochs_from_scratch_bs_128_noiseTrue'
g29_recognition_model_path: 'checkpoints/fragment-recognition-net_GCN-based_trained_on_sand_detection_dataset_bb_yolo_1000scenes_split_7-group_0029_using_lossCAT_for500epochs_from_scratch_bs_128_noiseTrue/model.pt'
dataset_root_path: '/home/palma/repair/sand_scenes'
#'/media/lucap/big_data/datasets/repair/sand_detection_dataset_bb_yolo_1000scenes'

